=head1 NAME

obexftp - Mobile Equipment file transfer tool

=head1 SYNOPSIS

B<obexftp> [I<OPTION>] [I<COMMANDS>]

=head1 DESCRIPTION

B<obexftp> is used to access files on mobile equipment,
i.e. cell phones. With B<obexftpd> you can transfer files between any
computers using B<IrDA>, B<Bluetooth> and B<TCP/IP>.

This tool lets you access the B<ObexFTP> library by the means of
a command line interface.
You might consider using the other means available.
E.g. the B<ObexFS> filesystem for Linux.

=head1 OPTIONS

The ordering of options is important. Every command will use the most
recent device set. Every file without command switch will apply to the
command given most recent. See B<EXAMPLES>

=head2 Transport Options

=over

=item B<-i>, B<--irda>

Connect using the IrDA protocol. This is the default.

=item B<-b> I<device>, B<--bluetooth> I<device>

Connect to this bluetooth device. If the device is not given the first
device found will be used.

=item B<-B> I<number>, B<--channel> I<number>

Use this bluetooth channel when connecting.
The channel will be discoverd automatically if this option is not used.

=item B<-d> I<no/address>, B<--hci> I<no/address>

Use the bluetooth device referenced by number or address as
source device for the connection.

=item B<-u> I<intf no>, B<--usb> I<intf no>

Connect to this usb interface or list all available usb interfaces.

=item B<-t> I<device>, B<--tty> I<device>

Connect to this tty device.

=item B<-n> I<host>, B<--network> I<host>

Connect to this network host.

=back


=head2 Compatibility Options

=over

=item B<-U> I<uuid>, B<--uuid> I<uuid>

Select the UUID to connect with. Recognized values are currently
"none" needed by some Nokia mobile devices,
"FBS" (default) for the normal file browsing service,
"IRMC" for IRMC synchronisation and
"S45" when connecting to a Siemens Mobile phone via cable or
"SHARP" for PCSOFTWARE UUID with Sharp devices.

=item B<-H>, B<--noconn>

Suppress connection IDs (i.e. send no connection header to the mobile).

=item B<-S>, B<--nopath>

Don't use "setpath" commands (i.e. send the whole path as filename to the
mobile).
Can be used together with B<--noconn> and B<--uuid none> to send an OBEX-PUSH.

=back


=head2 Setting The File Path

=over

=item B<-c> I<folder>, B<--chdir> I<folder>

Set the mobiles current working directory.

=item B<-C> I<folder>, B<--mkdir> I<folder>

Set the mobiles current working directory.
The folder will be created if it doesn't exist.

=item B<-l> I<folder>, B<--list> I<folder>

List a folder.

=back


=head2 Sending And Retrieving Files

=over

=item B<-o> I<path>, B<--output> I<path>

Specify the target file name, overriding the implicit local name from B<--get>
or the implicit remote name from B<--put>

=item B<-g> I<source>, B<--get> I<source>

Retrieve files from mobile.

=item B<-G> I<source>, B<--getdelete> I<source>

Retrieve files from mobile and delete them on the mobile

=item B<-p> I<source>, B<--put> I<source>

Send files to the mobile.

=item B<-k> I<source>, B<--delete> I<source>

Delete files from the mobile.

=back


=head2 Experimental Extras

=over

=item B<-X>, B<--capability>

Retrieve the capability object from the mobile (if available).

=Item B<-Y>, B<--probe>

Probe and report device characteristics

=item B<-x>, B<--info>

Retrieve misc infos from mobile. I.e. memory size and free memory.
Siemens specific for now.

=item B<-m> I<src> I<dest>, B<--move> I<src> I<dest>

Move (rename) files on the mobile. Siemens specific for now.

=back


=head2 Version Information And Help

=over

=item B<-v>, B<--verbose>

Be verbose and give some additional infos.

=item B<-V>, B<--version>

Print version string and exit.

=item B<-h>, B<--help>, B<--usage>

Print short usage instructions.

=back

=head1 EXAMPLES

=over

=item To get the directory listing from the first irda device:

B<obexftp -i -l>
or just
B<obexftp -l>
as IrDA is the default.

=item To get the file bar from directory foo from the first bluetooth device:

B<obexftp -b -c foo -g bar>

=item To send the file bar to directory foo with device on first serial port:

B<obexftp -t /dev/ttyS0 -c foo -p bar>

=item It is possible to use RfComm (serial port over bluetooth):

B<obexftp -t /dev/rfcomm0 -c foo -p bar>

=item And also IrComm (serial port over IrDA):

B<obexftp -t /dev/ircomm0 -c foo -p bar>

=item To send the file bar using plain OBEX PUSH:

B<obexftp --bluetooth --nopath --noconn --uuid none --put bar>


=back

=head1 SEE ALSO

L<obexftpd>(1), L<openobex>(3), L<obexftp>(3), L<multicobex>(3), L<libbfb>(3).

=head1 BUGS

Bugs ? Features !

=head1 NOTES

The software has been tested and reported working on at least Siemens, Ericsson, and Nokia phones.

=head1 AUTHOR

Christian W. Zuckschwerdt E<lt>zany@triq.netE<gt>

